### ISSUE TITLE
--run_ancestry pgsc_calc.tar.zst doesn't work

### ISSUE THREAD

**Issue by frahimov** [PGScatalog/pgsc_calc#175]
### Description of the bug

Hello, 
My analysis without _--run_ancestry_ works, but I when include "_--run_ancestry_ pgsc_calc.tar.zst" it fails. 
Download of the pgsc_calc.tar.zst folder went without any problems. Checksum is correct. I am attaching the log file. Could you please take a look?

### Command used and terminal output

```console
nextflow run pgscatalog/pgsc_calc -profile docker --input samplesheet.csv --target_build GRCh37 --pgs_id PGS000754 --min_overlap 0.0 --run_ancestry pgsc_calc.tar.zst
```

### Relevant files

[nextflow.log](https://github.com/PGScatalog/pgsc_calc/files/12715567/nextflow.log)

### System information

HPC with OS SUSE

**Comment by frahimov** [comment]
I did. I am not sure if the run got stuck or failed, because I do not see any exit status on Terminal. Here is the command and log file attached. 
nextflow run pgscatalog/pgsc_calc -profile docker --input samplesheet.csv --target_build GRCh37 --pgs_id PGS000754 --min_overlap 0.0 --only_match --run_ancestry pgsc_calc.tar.zst
[nextflow.log](https://github.com/PGScatalog/pgsc_calc/files/12717521/nextflow.log)

**Comment by frahimov** [comment]
Here is a new log file with --only_match
Full command:
nextflow run pgscatalog/pgsc_calc -profile docker --input samplesheet.csv --target_build GRCh37 --pgs_id PGS000754 --only_match  --run_ancestry pgsc_calc.tar.zst

[nextflow.log](https://github.com/PGScatalog/pgsc_calc/files/12717842/nextflow.log)

**Comment by nebfield** [comment]
> I have a feeling it has something to do with this:
> 
> Sep-25 10:08:37.657 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process `PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE (1)` is unable to find [UnixPath]: `/homes/rahimfx1/projects/immunology/sle/ttid_imm_profil_pgs/work/ref_extracted/deg2_hg38.king.cutoff.out.id` (pattern: `deg2_hg38.king.cutoff.out.id`) Sep-25 10:08:37.793 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE > Skipping output binding because one or more optional files are missing: fileoutparam<0:3> Sep-25 10:08:37.793 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Process PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE > Skipping output binding because one or more optional files are missing: fileoutparam<1:1>

This is should be OK. `EXTRACT_DATABASE` only extracts reference data that matches your target build, so GRCh38 stuff is missing (this is good to save space).

I'm unable to reproduce the problem using data in GRCh37 (UK Biobank) or GRCh38 (HGDP) on a HPC or my laptop 😢 

Some more things to try:

* Could you upload a copy your samplesheet please? Sometimes certain file names cause weird problems like this. 
* When you ran the calculator without the ancestry workflow, what were your match rates? (this information will be in the output report)

**Comment by frahimov** [comment]
Here is the samplesheet:
[samplesheet.csv](https://github.com/PGScatalog/pgsc_calc/files/12728370/samplesheet.csv)

Sample IDs are coded like this "205937930117_R10C02"

Match rate is 77.5. The strange this is that my first attempt without specifying overlap failed, but when I add the "--min-overlap 0.0" flag it WAS successfully completed. Any idea why it fails, even though the default overlap is 0.75?

[PGS Catalog Calculator (pgsc_calc) report.csv](https://github.com/PGScatalog/pgsc_calc/files/12728495/PGS.Catalog.Calculator.pgsc_calc.report.csv)

**Comment by nebfield** [comment]
Thanks! I can now reproduce the bug.

It seems VCF input to the ancestry subworkflow is broken 😬 I ran all of my ancestry tests with native plink bfiles or pfiles.  

A temporary fix would be to use plink to recode your VCFs manually. The workflow normally does this automatically:

```
$ plink2 --vcf <vcf_path> --make-pfile --out chr1.filtered
```

Then set up a samplesheet with the "pfile" or "bfile" format.

I'll investigate the bug properly and release a patch sometime in the next few days to fix the underlying problem.

> Match rate is 77.5. The strange thing is that my first attempt without specifying minimum overlap failed, but when I add the "--min-overlap 0.0" flag it was successfully completed. Any idea why it fails, even though the default overlap is 0.75?

It should have worked OK 🤔 your report looks good. If it happens consistently, please open a new issue. 

> BTW, the sample size is 118 (~50% EUR and ~50% AFR). Could small sample size be a problem for the ancestry analysis?

I think your data should be OK but @smlmbrt is the expert 😄

**Comment by frahimov** [comment]
Phew. Good to hear. Thank you for looking into this. Actually, I already have PLINK  files (bed, bim, fam). I will give it a try.

**Comment by frahimov** [comment]
got excited too fast. Sorry, the ancestry analysis does not with PLINK files either.
Here are log files without the --run_ancestry flag, which worked fine
[nextflow_no_ancestry.log](https://github.com/PGScatalog/pgsc_calc/files/12729294/nextflow_no_ancestry.log)
and with --run_ancestry that failed
[nextflow_with_ancestry.log](https://github.com/PGScatalog/pgsc_calc/files/12729297/nextflow_with_ancestry.log)

**Comment by frahimov** [comment]
With plink files the analysis worked without the --run_ancestry flag.
But this time I got different error messages with the --run_ancestry flag.
[nextflow_no_ancestry.log](https://github.com/PGScatalog/pgsc_calc/files/12729528/nextflow_no_ancestry.log)
[nextflow_with_ancestry.log](https://github.com/PGScatalog/pgsc_calc/files/12729529/nextflow_with_ancestry.log)
[samplesheet_plink.csv](https://github.com/PGScatalog/pgsc_calc/files/12729530/samplesheet_plink.csv)

**Comment by nebfield** [comment]
Exit code 137 means your job is being killed by your HPC because it's out of memory (8GB isn't enough to score that file). 

Try changing `process_low` to [use 16GB of RAM](https://pgsc-calc.readthedocs.io/en/latest/how-to/bigjob.html#configuring-pgsc-calc-to-use-more-resources-locally).

**Comment by frahimov** [comment]
That worked!! Thank you.

**Comment by AWS-crafter** [comment]
I got the same error, then I added the -c custom.config with processs_low to use 16 GB of RAM. After doing that, there was a different error:

```
[everything going as expected...]
[90/3b9c76] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1)                                               [  0%] 0 of 1
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCORE_REPORT                                                        -
[4b/ab791b] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS (1)                                                   [  0%] 0 of 1
ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1)` terminated with an error exit status (1)

Command executed:

  # TODO: --ref_pcs is a horrible hack to select the first duplicate
  ancestry_analysis -d dante         -r reference         --psam GRCh37_1000G_ALL.psam         --ref_pcs ref_pcs/1.pcs         --target_pcs target_pcs/*.pcs         -x deg2_phase3.king.cutoff.out.id         -p SuperPop         -s aggregated_scores.txt.gz         -a RandomForest         --n_popcomp 5         -n empirical mean mean+var         --n_normalization 4         --outdir .         -v
  
  cat <<-END_VERSIONS > versions.yml
  ANCESTRY_ANALYSIS:
      pgscatalog_utils: $(echo $(python -c 'import pgscatalog_utils; print(pgscatalog_utils.__version__)'))
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)
executor >  local (18)
[c4/156ceb] process > PGSCATALOG_PGSCALC:PGSCALC:DOWNLOAD_SCOREFILES ([pgs_id:PGS003725, pgp_id:, trait_efo:])              [100%] 1 of 1 ✔
[49/3e1a68] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:SAMPLESHEET_JSON (dante_samplesheet_pfile.csv)                 [100%] 1 of 1 ✔
[db/c88021] process > PGSCATALOG_PGSCALC:PGSCALC:INPUT_CHECK:COMBINE_SCOREFILES (1)                                         [100%] 1 of 1 ✔
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELBIM                                          -
[skipped  ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_RELABELPVAR (dante chromosome ALL)                  [100%] 1 of 1, stored: 1 ✔
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:MAKE_COMPATIBLE:PLINK2_VCF                                                 -
[skipped  ] process > PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:EXTRACT_DATABASE (1)                                      [100%] 1 of 1, stored: 1 ✔
[skipped  ] process > PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:INTERSECT_VARIANTS (dante chromosome ALL)                 [100%] 1 of 1, stored: 1 ✔
[d4/cece30] process > PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:FILTER_VARIANTS (dante GRCh37)                            [100%] 1 of 1 ✔
[56/61d6f1] process > PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:PLINK2_MAKEBED_REF (reference chromosome)                 [100%] 1 of 1 ✔
[skipped  ] process > PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:INTERSECT_THINNED (dante)                                 [100%] 1 of 1, stored: 1 ✔
[b0/970c2d] process > PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:RELABEL_IDS (dante pvar)                                  [100%] 1 of 1 ✔
[8d/f0516c] process > PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:PLINK2_MAKEBED_TARGET (dante chromosome)                  [100%] 1 of 1 ✔
[19/5711ab] process > PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:PLINK2_ORIENT (dante)                                     [100%] 1 of 1 ✔
[a4/64eb37] process > PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:FRAPOSA_PCA (reference)                                   [100%] 1 of 1 ✔
[skipped  ] process > PGSCATALOG_PGSCALC:PGSCALC:ANCESTRY_PROJECT:FRAPOSA_PROJECT (dante)                                   [100%] 1 of 1, stored: 1 ✔
[5f/cc49c9] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_VARIANTS (dante chromosome ALL)                                [100%] 1 of 1 ✔
[b7/749c29] process > PGSCATALOG_PGSCALC:PGSCALC:MATCH:MATCH_COMBINE (dante)                                                [100%] 1 of 1 ✔
[e2/98946a] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:RELABEL_SCOREFILE_IDS (dante scorefile)                        [100%] 1 of 1 ✔
[3e/764947] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:RELABEL_AFREQ_IDS (dante afreq)                                [100%] 1 of 1 ✔
[3a/58afd3] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:PLINK2_SCORE (reference chromosome ALL effect type additive 0) [100%] 2 of 2 ✔
[f9/4ee72c] process > PGSCATALOG_PGSCALC:PGSCALC:APPLY_SCORE:SCORE_AGGREGATE (dante)                                        [100%] 1 of 1 ✔
[90/3b9c76] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1)                                               [100%] 1 of 1, failed: 1 ✘
[-        ] process > PGSCATALOG_PGSCALC:PGSCALC:REPORT:SCORE_REPORT                                                        -
[4b/ab791b] process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS (1)                                                   [  0%] 0 of 1
Execution cancelled -- Finishing pending tasks before exit
ERROR ~ Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1)` terminated with an error exit status (1)

Command executed:

  # TODO: --ref_pcs is a horrible hack to select the first duplicate
  ancestry_analysis -d dante         -r reference         --psam GRCh37_1000G_ALL.psam         --ref_pcs ref_pcs/1.pcs         --target_pcs target_pcs/*.pcs         -x deg2_phase3.king.cutoff.out.id         -p SuperPop         -s aggregated_scores.txt.gz         -a RandomForest         --n_popcomp 5         -n empirical mean mean+var         --n_normalization 4         --outdir .         -v
  
  cat <<-END_VERSIONS > versions.yml
  ANCESTRY_ANALYSIS:
      pgscatalog_utils: $(echo $(python -c 'import pgscatalog_utils; print(pgscatalog_utils.__version__)'))
  END_VERSIONS

Command exit status:
  1

Command output:
  (empty)

Command error:
  root: 2023-09-26 23:33:09 DEBUG    Verbose logging enabled
  pgscatalog_utils.ancestry.read: 2023-09-26 23:33:09 DEBUG    Reading PCA projection: ref_pcs/1.pcs
  pgscatalog_utils.ancestry.read: 2023-09-26 23:33:09 DEBUG    Initialising combined DF
  pgscatalog_utils.ancestry.read: 2023-09-26 23:33:09 DEBUG    Filtering to relevant PCs
  pgscatalog_utils.ancestry.read: 2023-09-26 23:33:09 DEBUG    Flagging related samples with: deg2_phase3.king.cutoff.out.id
  pgscatalog_utils.ancestry.read: 2023-09-26 23:33:09 DEBUG    Reading PCA projection: target_pcs/001.pcs
  pgscatalog_utils.ancestry.read: 2023-09-26 23:33:09 DEBUG    Initialising combined DF
  pgscatalog_utils.ancestry.read: 2023-09-26 23:33:09 DEBUG    Filtering to relevant PCs
  pgscatalog_utils.ancestry.read: 2023-09-26 23:33:09 DEBUG    Reading aggregated score data: aggregated_scores.txt.gz
  Traceback (most recent call last):
    File "/venv/bin/ancestry_analysis", line 8, in <module>
      sys.exit(ancestry_analysis())
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/ancestry/ancestry_analysis.py", line 42, in ancestry_analysis
      ancestry_ref, ancestry_target, compare_info = compare_ancestry(ref_df=reference_df,
    File "/venv/lib/python3.10/site-packages/pgscatalog_utils/ancestry/tools.py", line 79, in compare_ancestry
      mwu_pc = mannwhitneyu(ref_train_df[col_pc], target_df[col_pc])
    File "/venv/lib/python3.10/site-packages/scipy/stats/_axis_nan_policy.py", line 503, in axis_nan_policy_wrapper
      res = hypotest_fun_out(*samples, **kwds)
    File "/venv/lib/python3.10/site-packages/scipy/stats/_mannwhitneyu.py", line 460, in mannwhitneyu
      _mwu_input_validation(x, y, use_continuity, alternative, axis, method))
    File "/venv/lib/python3.10/site-packages/scipy/stats/_mannwhitneyu.py", line 203, in _mwu_input_validation
      raise ValueError('`x` and `y` must be of nonzero size.')
  ValueError: `x` and `y` must be of nonzero size.

Work dir:
  /home/ubuntu/pgsc_calc/work/90/3b9c761ac0ba7ebb4b64aa470c7685

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

 -- Check '.nextflow.log' file for details
ERROR ~ ERROR: No results report written!

 -- Check '.nextflow.log' file for details
```

.nextflow.log:
```
[...]
Sep-26 23:33:09.777 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 23; name: PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1); status: COMPLETED; exit: 1; error: -; workDir: /home/ubuntu/pgsc_calc/work/90/3b9c761ac0ba7ebb4b64aa470c7685]
Sep-26 23:33:09.780 [Task submitter] DEBUG n.executor.local.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Sep-26 23:33:09.780 [Task monitor] DEBUG nextflow.processor.TaskProcessor - Handling unexpected condition for
  task: name=PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1); work-dir=/home/ubuntu/pgsc_calc/work/90/3b9c761ac0ba7ebb4b64aa470c7685
  error [nextflow.exception.ProcessFailedException]: Process `PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1)` terminated with an error exit status (1)
Sep-26 23:33:09.780 [Task submitter] INFO  nextflow.Session - [4b/ab791b] Submitted process > PGSCATALOG_PGSCALC:PGSCALC:DUMPSOFTWAREVERSIONS (1)
Sep-26 23:33:09.791 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1)'

Caused by:
  Process `PGSCATALOG_PGSCALC:PGSCALC:REPORT:ANCESTRY_ANALYSIS (1)` terminated with an error exit status (1)
[...]
```

This was in pfile format on build hg19. It seems like the Mann–Whitney U test function within the pgscatalog_utils.ancestry.tools.compare_ancestry function is being called with empty datasets for some reason (target_df[col_pc] is empty).

I adding some [ancestry option](https://pgsc-calc.readthedocs.io/en/latest/reference/params.html#ancestry-options) might fix this. I am okay with using the closest ancestry group as opposed to the PC regression method, or whatever other methods would fix this / skip the test.

**Comment by tkamth** [comment]
@nebfield, I am not sure if this is a related problem but I am getting a segmentation fault at the plink2_vcf step.  Any insight on which parameter to change?

`terminated with error exit status (139)

GRCh38__test_ancestry_ALL-temporary.pvar.zst +
  GRCh38__test_ancestry_ALL-temporary.psam written.
  202 samples (0 females, 0 males, 202 ambiguous; 202 founders) loaded from
  GRCh38__test_ancestry_ALL-temporary.psam.
  Warning: 31828 variant IDs erased by --set-all-var-ids due to allele code
  length.
  134293252 variants loaded from
  GRCh38__test_ancestry_ALL-temporary.pvar.zst.
  Note: No phenotype data present.
  Calculating sample missingness rates... done.
  Calculating allele frequencies... done.
  --missing: Sample missing data report written to
  GRCh38__test_ancestry_ALL.smiss .
  --missing variant report: 99%
  --missing: Variant missing data report written to
  GRCh38__test_ancestry_ALL.vmiss .
  134293252 variants remaining after main filters.
  Writing GRCh38__test_ancestry_ALL.psam ... done.
  Writing GRCh38__test_ancestry_ALL.pvar.zst ... 0%.command.sh: line 11: 3979724 Segmentation fault      (core dumped) plink2 --threads 8 --memory 32768 --set-all-var-ids '@:#:$r:$a' --max-alleles 2 --missing vcols=fmissdosage,fmiss --new-id-max-allele-len 100 missing --vcf _GSAv3+.imputed.vcf.gz --make-pgen vzs --out GRCh38__test_ancestry_ALL
  cp: '.command.out' and '.command.out' are the same file
  cp: '.command.err' and '.command.err' are the same file
  cp: '.command.trace' and '.command.trace' are the same file`

**Comment by nebfield** [comment]
> @nebfield, I am not sure if this is a related problem but I am getting a segmentation fault at the plink2_vcf step. Any insight on which parameter to change?

The bug described in this issue is a problem with the workflow, not plink. A segfault is an internal plink problem.

Until we release a patch I'd recommend preparing your input genomes by [converting your VCF in the terminal using plink](https://pgsc-calc.readthedocs.io/en/latest/how-to/prepare.html#vcf-from-an-imputation-server). Then run the workflow with `pfile` input 😄 

Feel free to open a new issue if you have any problems.

**Comment by nebfield** [comment]
[fixed in the latest release](https://github.com/PGScatalog/pgsc_calc/releases/tag/v2.0.0-alpha.3). thanks for the bug report!

**Comment by tkamth** [comment]
Dear team, thanks but unfortunately I am still getting an segmentation fault on my end which appears to be linked to the older plink2.0 version used.  Would it be possible to update the nextflow pipeline with the updated plink2 alpha 5.0 singularity image? 

Thanks,

Tony

**Comment by smlmbrt** [comment]
@tkamth - could you share the segmentation fault error you're getting from plink? It is possible that it is from under allocated memory.
